### ISSUE TITLE
Issues with Getting SpriteSomething to Run on Mac

### ISSUE THREAD

**Issue by LancetheGallade1500** [Artheau/SpriteSomething#85]
(I'll just copy what I posted on the Reddit page.)

So, I've been trying to use SpriteSomething for a while now, but it won't even open. The program pops up and I can see its feather icon, but it has an error before I can even do anything.

I have a Mac that runs Mojave. I first tried it with version 1.42.62012324, both via Terminal and Python, but I got these error messages:

Terminal
```
While running, encountered fatal error: KEYERROR
('noun',)
Traceback (most recent call last):
 File "SpriteSomething.py", line 21, in run_GUI
 File "source/meta/gui/gui.py", line 41, in make_GUI
 File "source/meta/gui/gui.py", line 89, in __init__
 File "source/meta/gui/gui.py", line 123, in create_random_title
KeyError: 'noun'
```
Python:
```
 While running, encountered fatal error: TYPEERROR
("'NoneType' object is not subscriptable",)
```
I saw that the MacOSX executable said it was built on 10.15, so I assumed that maybe there was some kind of conflict between Mojave and Catalina. I downloaded the previous version, 1.0.659, built on 10.14, but I also got error messages. The Python error was the same as above, but it wouldn't even open the program when I tried Terminal. I got this error within Terminal:
```
TypeError: expected str, bytes or os.PathLike object, not NoneType
[3704] Failed to execute script SpriteSomething
```

**Comment by miketrethewey** [comment]
Work attempted in 6ef6df4 .

**Comment by miketrethewey** [comment]
@LancetheGallade1500 Is this still an issue with 1.46.x?

**Comment by LancetheGallade1500** [comment]
Running it in Terminal gives a similar message as before, albeit with different lines listed in the traceback:

<img width="532" alt="Screen Shot 2021-01-05 at 11 21 37 AM" src="https://user-images.githubusercontent.com/48635148/103689629-70953b80-4f48-11eb-95ab-cf87547a5358.png">

I'll try it with Python later, I have class in a bit.
